# Generated by Django 6.0.7 on 2026-07-27 06:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Protocols',
            fields=[
                ('protocol_id', models.AutoField(primary_key=True, serialize=False)),
                ('protocol_name', models.CharField(max_length=100, unique=True)),
                ('protocol_port', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol_category', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('NETWORK', 'Networking'), ('IOT', 'IoT'), ('RADIO', 'Radio'), ('THICK', 'Thick Client'), ('SOURCE', 'Source Code Analysis')], max_length=30)),
                ('protocol_type', models.CharField(choices=[('APPLICATION', 'Application Protocol'), ('NETWORK', 'Network Protocol'), ('TRANSPORT', 'Transport Protocol'), ('SESSION', 'Session Protocol'), ('SECURITY', 'Security Protocol'), ('AUTHENTICATION', 'Authentication Protocol'), ('AUTHORIZATION', 'Authorization Protocol'), ('REMOTE_ACCESS', 'Remote Access Protocol'), ('FILE_TRANSFER', 'File Transfer Protocol'), ('DIRECTORY_SERVICE', 'Directory Service Protocol'), ('MESSAGING', 'Messaging Protocol'), ('API', 'API Protocol'), ('RPC', 'RPC Protocol'), ('WEB_SERVICE', 'Web Service Protocol'), ('COMMUNICATION', 'Communication Protocol'), ('INDUSTRIAL_CONTROL', 'Industrial Control Protocol'), ('INDUSTRIAL_AUTOMATION', 'Industrial Automation Protocol'), ('PLC_COMMUNICATION', 'PLC Communication Protocol'), ('BUILDING_AUTOMATION', 'Building Automation Protocol'), ('AUTOMOTIVE_COMMUNICATION', 'Automotive Communication Protocol'), ('IOT', 'IoT Protocol'), ('WIRELESS_COMMUNICATION', 'Wireless Communication Protocol'), ('ROUTING', 'Routing Protocol'), ('NETWORK_MANAGEMENT', 'Network Management Protocol'), ('NAME_RESOLUTION', 'Name Resolution Protocol'), ('CONFIGURATION', 'Configuration Protocol'), ('TIME_SYNCHRONIZATION', 'Time Synchronization Protocol'), ('VPN', 'VPN Protocol'), ('TUNNELING', 'Tunneling Protocol'), ('STREAMING', 'Streaming Protocol'), ('PUSH_NOTIFICATION', 'Push Notification Protocol'), ('MIDDLEWARE', 'Middleware Protocol'), ('SMART_CARD', 'Smart Card Protocol'), ('PAYMENT', 'Payment Protocol'), ('CRYPTOGRAPHIC', 'Cryptographic Protocol'), ('DEBUGGING', 'Debugging Protocol'), ('HARDWARE_INTERFACE', 'Hardware Interface Protocol'), ('SERIAL_COMMUNICATION', 'Serial Communication Protocol'), ('BUS_COMMUNICATION', 'Bus Communication Protocol'), ('PROPRIETARY', 'Proprietary Protocol')], max_length=30)),
                ('protocol_desc', models.TextField(blank=True)),
                ('osi_layer', models.CharField(choices=[('LAYER1', 'Physical'), ('LAYER2', 'Data Link'), ('LAYER3', 'Network'), ('LAYER4', 'Trasport'), ('LAYER5', 'Session'), ('LAYER6', 'Presentation'), ('LAYER7', 'Application')], max_length=30)),
                ('transport_protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('TCP/UDP', 'TCP/UDP'), ('QUIC', 'QUIC'), ('HTTP', 'HTTP'), ('HTTP/2', 'HTTP/2'), ('HTTP/3', 'HTTP/3'), ('HTTPS', 'HTTPS'), ('IP', 'IP'), ('TCP_IP', 'TCP/IP'), ('ETHERNET', 'Ethernet'), ('CAN', 'CAN'), ('CAN_FD', 'CAN FD'), ('LIN', 'LIN'), ('FLECRAY', 'FlexRay'), ('SPI', 'SPI'), ('I2C', 'I2C'), ('UART', 'UART'), ('USB', 'USB'), ('BLE', 'Bluetooth'), ('WIFI', 'Wi-Fi'), ('RF', 'RF'), ('LORA', 'LoRa'), ('NFC', 'NFC'), ('RS232', 'RS232'), ('RS485', 'RS485'), ('SERIAL', 'Serial'), ('UNIX_SOCKET', 'Unix Socket'), ('SMB', 'SMB'), ('RPC', 'RPC'), ('DCOM', 'DCOM')], max_length=30)),
                ('default_ports', models.CharField(blank=True, choices=[('', '')], max_length=30, null=True)),
                ('serial_port', models.CharField(blank=True, max_length=20, null=True)),
                ('secure_ports', models.CharField(choices=[('22', '22 (SSH/SFTP)'), ('443', '443 (HTTPS/TLS)'), ('465', '465 (SMTPS)'), ('636', '636 (LDAPS)'), ('853', '853 (DNS over TLS)'), ('989', '989 (FTPS Data)'), ('990', '990 (FTPS Control)'), ('992', '992 (Secure Telnet)'), ('993', '993 (IMAPS)'), ('995', '995 (POP3S)'), ('1813', '1813 (RADIUS Accounting)'), ('4500', '4500 (IPsec NAT-T)'), ('51820', '51820 (WireGuard)'), ('VENDER_SPECIFIC', 'Vendor Specific'), ('CARRIER_ASSIHN', 'Carrier Assigned')], max_length=30)),
                ('communication_model', models.CharField(choices=[('CLIENT_SERVER', 'Client Server'), ('PEER_TO_PEER', 'Peero-to-Peer'), ('PUBLISH_SUBSCR', 'Publish-Subscribe'), ('REQU_RESPO', 'Request-Response'), ('MASTER_SLAVE', 'Master-Slave'), ('BUS_COMM', 'Bus Communication'), ('BROADCAST', 'Broadcast'), ('MULTICAST', 'Multicast'), ('UNICAST', 'Unicast'), ('MESH_NETWORK', 'Mesh Network')], max_length=30)),
                ('used_in', models.CharField(choices=[('WEB_APP', 'Web Applications'), ('WEB_SERVER', 'Web Services'), ('REST_API', 'REST APIs'), ('GRAPHQL', 'GraphQL APIs'), ('MICROSERVICES', 'Microservices'), ('ENTERPRISE_NETWORK', 'Enterprise Networks'), ('MOBILE_APP', 'Mobile Applications'), ('DESKTOP_APP', 'Desktop Applications'), ('IOT', 'IoT'), ('EMBEDDED_SYS', 'Embedded Systems'), ('SCADA', 'SCADA'), ('INDUSTRIAL_AUTO', 'Industrial Automation'), ('CLOUD', 'Cloud'), ('AUTOMOTIVE', 'Automotive'), ('BUILDING_AUTO', 'Building Automation'), ('PYMENT_SYS', 'Payment Systems'), ('VOIP', 'VoIP'), ('VPN', 'VPN')], max_length=30)),
                ('used_by', models.CharField(choices=[('BROWSER', 'Browser'), ('WEB_SERVER', 'Web Server'), ('APP_SERVER', 'Application Server'), ('DATABASE_SERVER', 'Database Server'), ('DESKTOP', 'Desktop'), ('LAPTOP', 'Laptop'), ('MOBILE', 'Mobile'), ('FIREWALL', 'Firewall'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('PLC', 'PLC'), ('RTU', 'RTU'), ('ECU', 'ECU'), ('IOT_GATEWAY', 'IoT Gateway'), ('IOT_SENSOR', 'IoT Sensor'), ('CLOUD_SERVER', 'Cloud Server'), ('SMART_CARD', 'Smart Card'), ('RFID_READER', 'RFID Reader'), ('PYMENT_TERMINAL', 'Payment Terminal')], max_length=30)),
                ('purpose', models.TextField(blank=True)),
                ('data_format', models.CharField(choices=[('TEXT', 'Text'), ('BINARY', 'Binary'), ('JSON', 'JSON'), ('XML', 'XML'), ('YAML', 'YAML'), ('CSV', 'CSV'), ('ASN_1', 'ASN.1'), ('PROTOCOL_BUFFERS', 'Protocol Buffers'), ('RAW_BYTES', 'Raw Bytes'), ('FRAMES', 'Frames')], max_length=30)),
                ('packet_structure', models.CharField(choices=[('HEADER_PAYLOAD', 'Header + Payload'), ('REQU_RESP', 'Request / Response'), ('FRAME_BASED', 'Frame Based'), ('BINARY_FRAME', 'Binary Frame'), ('BINARY_MSG', 'Binary Message'), ('XML_ENVELOPE', 'XML Envelope'), ('JSON_MSG', 'JSON Message'), ('CUSTOM_FORMAR', 'Custom Format')], max_length=30)),
                ('protocol_authentication', models.CharField(choices=[('BASIC', 'Basic'), ('DIGEST', 'Digest'), ('NTLM', 'NTLM'), ('KERBEROS', 'Kerberos'), ('OAUTH_2.0', 'OAuth 2.0'), ('JWT', 'JWT'), ('OPENID_CONN', 'OpenID Connect'), ('SAML', 'SAML'), ('API_KEY', 'API Key'), ('CERTIFICATE', 'Certificate'), ('USERNAME_PASS', 'Username/Password'), ('TOKEN', 'Token Based'), ('MFA', 'MFA')], max_length=30)),
                ('emcryption', models.CharField(choices=[('SSL', 'SSL'), ('TLS', 'TLS'), ('TLS_1.2', 'TLS 1.2'), ('TLS_1.3', 'TLS 1.3'), ('DTLS', 'DTLS'), ('IP_SEC', 'IPsec'), ('AES', 'AES'), ('RSA', 'RSA'), ('ECC', 'ECC'), ('CHACHA20', 'ChaCha20')], max_length=30)),
                ('standard_rfc', models.CharField(choices=[('RFC', 'RFC'), ('IEEE', 'IEEE'), ('ISO', 'ISO'), ('IEC', 'IEC'), ('IETF', 'IETF'), ('W3C', 'W3C'), ('BLE_SIG', 'Bluetooth SIG'), ('OASIS', 'OASIS'), ('CAN_IN_AUTO', 'CAN in Automation'), ('OPC_FOUNDATION', 'OPC Foundation'), ('NIST', 'NIST')], max_length=30)),
            ],
            options={
                'db_table': 'Protocols',
                'ordering': ['protocol_name'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='V1', max_length=10)),
                ('unique_id', models.CharField(max_length=4)),
                ('sub_module', models.CharField(blank=True, max_length=2)),
                ('requirement_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('roleId', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.CharField(max_length=20, unique=True)),
                ('stage_name', models.CharField(choices=[('INFO', 'Information Gathering'), ('SCAN', 'Scanning & Enumeration'), ('VULN', 'Vulnerability Assessment'), ('EXPLOIT', 'Exploitation'), ('POST', 'Post Exploitation')], max_length=50)),
                ('stage_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=20)),
                ('standard_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_id', models.CharField(max_length=20, unique=True)),
                ('suite_name', models.CharField(max_length=100)),
                ('suite_code', models.CharField(max_length=20)),
                ('std_follows', models.CharField(max_length=50)),
                ('suite_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.CharField(max_length=20, unique=True)),
                ('tool_name', models.CharField(max_length=50, unique=True)),
                ('tool_desc', models.TextField(blank=True)),
                ('tool_category', models.CharField(choices=[('SOFTWARE', 'Software Tool'), ('HARDWARE', 'Hardware Tool')], max_length=20)),
                ('command_supported', models.BooleanField(default=True)),
                ('tool_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TEST_MANAGER', 'Test Manager'), ('TESTER', 'Tester'), ('CUSTOMER', 'Customer'), ('SUPPORTADMIN', 'Support Admin'), ('MASTER', 'Master')], default='CUSTOMER', max_length=20)),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('totp_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('WEBAPP', 'Web Application'), ('MOBILE', 'Mobile'), ('NETWORK', 'Network'), ('IOT', 'IOT'), ('RADIO', 'Radio'), ('THICK', 'Thick Client'), ('SOURCE', 'Source Code Analysis')], max_length=20)),
                ('project_desc', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('TESTING', 'Testing'), ('REPORT_PENDING', 'Report Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], max_length=30)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('progress', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_projects', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'TEST_MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.project')),
                ('tester', models.ForeignKey(limit_choices_to={'role': 'TESTER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.TextField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.project')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('report_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.project')),
            ],
        ),
        migrations.CreateModel(
            name='TemporarySuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('expiry_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_temp_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToolParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('parameter_label', models.CharField(max_length=100)),
                ('parameter_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('file', 'File')], max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('default_value', models.CharField(blank=True, max_length=200, null=True)),
                ('options', models.TextField(blank=True, help_text='Comma separated values', null=True)),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=1)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='account.tools')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_token', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('device', models.CharField(default='unknown', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=20, unique=True)),
                ('vuln_title', models.CharField(max_length=250)),
                ('vuln_category', models.CharField(max_length=150)),
                ('vuln_desc', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('cvss_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cwe', models.CharField(blank=True, max_length=50)),
                ('cve', models.CharField(blank=True, max_length=50)),
                ('affected_component', models.TextField()),
                ('remediation', models.TextField()),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('RECORDED', 'Recorded'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.project')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_vulnerabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='SuiteStageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.stages')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.suites')),
            ],
            options={
                'unique_together': {('suite', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='ToolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.stages')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.suites')),
                ('hardware_required', models.ManyToManyField(blank=True, related_name='hardware_dependencies', to='account.tools')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tools')),
            ],
            options={
                'unique_together': {('suite', 'stage', 'tool')},
            },
        ),
    ]
