# Generated by Django 6.0.6 on 2026-08-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('WEBAPP', 'Web Application'), ('MOBILE', 'Mobile'), ('NETWORK', 'Network'), ('IOT', 'IOT'), ('EMBEDDED', 'Embedded'), ('THICK', 'Thick Client'), ('SOURCE', 'Source Code Analysis')], max_length=20),
        ),
    ]
