# Generated by Django 6.0.7 on 2026-08-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('WEBAPP', 'Web Application'), ('MOBILE', 'Mobile'), ('NETWORK', 'Network'), ('EMBEDDED', 'Embedded'), ('RADIO', 'Radio'), ('THICK', 'Thick Client'), ('SOURCE', 'Source Code Analysis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='protocols',
            name='protocol_category',
            field=models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('NETWORK', 'Networking'), ('EMBEDDED', 'Embedded'), ('RADIO', 'Radio'), ('THICK', 'Thick Client'), ('SOURCE', 'Source Code Analysis')], max_length=30),
        ),
    ]
