# Generated by Django 6.0.7 on 2026-07-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_contact_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED_PENDING', 'Tester Assigned Pending'), ('TESTER_ASSIGNED', 'Tester Assigned'), ('TESTING', 'Testing'), ('REPORT_PENDING', 'Report Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], max_length=30),
        ),
    ]
