# Generated by Django 6.0.7 on 2026-08-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_project_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('WEB', 'Web Application'), ('MOBILE', 'Mobile'), ('NETWORK', 'Network'), ('EMBEDDED', 'Embedded'), ('RADIO', 'Radio'), ('THICK', 'Thick Client'), ('SOURCE', 'Source Code Analysis')], max_length=20),
        ),
    ]
