# Generated by Django 6.0.7 on 2026-07-27 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='assigned_by',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'TEST_MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='tester_assignments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='account.project'),
        ),
    ]
