# Generated by Django 6.0.7 on 2026-07-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_projectassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='testing_stage',
            field=models.CharField(choices=[('INFO', 'Information Gathering'), ('SCAN', 'Scanning'), ('VULN', 'Vulnerability Assessment'), ('EXPLOIT', 'Exploitation'), ('POST', 'Post Exploitation'), ('COMPLETED', 'Completed')], default='INFO', max_length=20),
        ),
    ]
