# Generated by Django 6.0.7 on 2026-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_project_testing_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_stage',
            field=models.CharField(default='INFO', max_length=20),
        ),
    ]
