# Generated by Django 6.0.7 on 2026-07-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_project_current_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('WEBAPP', 'Web Application'), ('MOBILE', 'Mobile'), ('NETWORK', 'Network'), ('IOT', 'IOT'), ('THICK', 'Thick Client'), ('SOURCE', 'Source Code Analysis')], max_length=20),
        ),
    ]
